---
title: "hw5"
format: 
  html: default
  pdf: default
author: Me
---

```{r}
library(tidyverse)
library(httr2)
library(rvest)
library(gganimate)
library(gifski)
library(jsonlite)
```

# Task 1
```{r}
f1_drivers <- c("alexander-albon", "fernando-alonso", "andkimi-antonelli", 
                  "oliver-bearman", "gabriel-bortoleto", "franco-colapinto", 
                  "jack-doohan", "pierre-gasly", "isack-hadjar", 
                  "lewis-hamilton", "nico-hulkenberg", "liam-lawson", 
                  "charles-leclerc", "lando-norris", "esteban-ocon", 
                  "oscar-piastri", "george-russell", "carlos-sainz", 
                  "lance-stroll", "yuki-tsunoda", "max-verstappen")


color <- c(
  "george-russell" = "#00D2BE",
  "andkimi-antonelli" = "#00D2BE",
  "lewis-hamilton" = "#DC0000",
  "charles-leclerc" = "#DC0000",
  "lando-norris" = "#FF8700",
  "oscar-piastri" = "#FF8700",
  "fernando-alonso" = "#006F62",
  "lance-stroll" = "#006F62",
  "max-verstappen" = "#3671C6",
  "liam-lawson" = "#3671C6",
  "pierre-gasly" = "#0090FF",
  "franco-colapinto" = "#0090FF",
  "oliver-bearman" = "#B6BABD",
  "esteban-ocon" = "#B6BABD",
  "alexander-albon" = "#005AFF",
  "carlos-sainz" = "#005AFF",
  "yuki-tsunoda" = "#6692FF",
  "isack-hadjar" = "#6692FF",
  "nico-hulkenberg" = "#2CD833",
  "gabriel-bortoleto" = "#2CD833"
)
gran <- c(
"Australian",
  "Chinese",
  "Japanese",
  "Bahrain",
  "Saudi Arabian",
  "Miami",
  "Emilia Romagna",
  "Monaco",
  "Spanish",
  "Canadian",
  "Austrian",
  "British",
  "Belgian",
  "Hungarian",
  "Dutch",
  "Italian",
  "Azerbaijan",
  "Singapore",
  "United States",
  "Mexico City",
  "São Paulo",
  "Las Vegas",
  "Qatar",
  "Abu Dhabi"
)




```

```{r}
results_table <- tibble(
  Driver = character(),
  Race_Number = integer(),
  Cumulative_Pts = double()
)



for (i in 1:(length(f1_drivers))) {
  a <- strsplit(f1_drivers[[i]], "-")[[1]] |> 
  substr(1, 3) |> 
  paste0(collapse = "") |> toupper()

url <- paste0("https://www.formula1.com/en/results/2025/drivers/",a,"01/",f1_drivers[[i]])


help_table <- read_html(url) |>
  html_element(".Table-module_table__cKsW2") |>
  html_table() |> mutate(
    Driver = f1_drivers[[i]],
    Race_number = row_number(),
    points_sum = cumsum(Pts.)
  ) |> select(Driver:points_sum)


results_table <-  rbind(results_table,help_table)
}


```
Візуалізація очок в персональному заліку в чемпіонаті після кожної з гонок

```{r}
results_table


ranked_results <- results_table |> 
  group_by(Race_number) |> 
  mutate(rank = rank(-points_sum, ties.method = "first"),
         index = map_chr(Driver, ~strsplit(.x,"-")[[1]][2]) |>substr(1,3) |> toupper()) |> 
  ungroup()


anim <- ggplot(ranked_results, 
               aes(x = rank, 
                   y = points_sum, 
                   fill = Driver,
                   group = Driver)) +
  geom_bar(stat = "identity") + scale_fill_manual(values = color)+
  geom_text(
  aes(label = paste0(round(as.integer(points_sum))), vjust = -1), 
  size = 4)+
  geom_text(aes(y = points_sum, label = index),size = 4, vjust = 1)+
  
  transition_states(
    states = Race_number, 
    transition_length = 2,
    state_length = 1
  ) +
  ease_aes() +
  
  labs(title = "{gran[as.integer(closest_state)]}",
       x = NULL,
       y = NULL) + 
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 20, face = "bold"),
    axis.text.y = element_blank(), 
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid = element_blank(),
    axis.text.x = element_blank()
  )


 animate(anim, nframes = 300, fps = 15, width = 1000, height = 700,units = "px",renderer = gifski_renderer())


```

# Task 2
Візуалізація швидкості піт стопів за 2025 рік 
Мене забанили і я не встиг перевірити чи цей код працює, він працював на окремо завантаженій одній гонці.
```{r}


sessions_url <- "https://api.openf1.org/v1/sessions?year=2025&session_name=Race"
all_race_keys <- request(sessions_url) |>
  req_perform() |>
  resp_body_json(simplifyVector = TRUE) |>
  as_tibble() |>
  pull(session_key)

pit_stops <- tibble()


for (i in all_race_keys) {
  url <- paste0("https://api.openf1.org/v1/pit?session_key=", i)
  pit <- request(url) |>
  req_perform() |>
  resp_body_json(simplifyVector = TRUE) |>
  as_tibble() |> mutate(pit_duration = pit_duration - mean(pit_duration))

  pit_stops <- rbind(pit_stops,pit)
  Sys.sleep(5)
}
 
  pit_stops |> filter(driver_number %in% c(4,81)) |> 
  ggplot( aes(x = factor(driver_number), y = pit_duration)) +
  geom_boxplot()+geom_jitter(width = 0.1,alpha = 0.5,color = "red")+
  theme_minimal()+
  labs(
    title = "Піт стопи за 2025",
    x = "номер гонщика",
    y = "тривалість піт стопа відносно середнього за гонку"  )



```


